version: '3.9'
services:
  db:
    container_name: ft_transcendence-db
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_DB=transcendence
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  back:
    container_name: ft_transcendence-back
    build:
      context: .
      dockerfile: docker/back.Dockerfile
    ports:
      - 8080:8080

  front:
    container_name: ft_transcendence-front
    build:
      context: ui/.
      dockerfile: ../docker/front.Dockerfile
    ports:
      - 3000:3000

volumes:
  db:
    driver: local
