on: [push]
jobs:
  back_build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install    
        env:
          CI: true
      - name: Generate build

        run: npm run build

  front_build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Install dependencies
        run: |
          cd ui/
          npm i -g rimraf
          npm install
        env:
          CI: true
      - name: Generate build
        run: npm run build
